# Agents
#
# Agents follow standard CrewAI config with the addition of the `toolsets` key
# in the schema. This will be matched to the toolsets in `tools` to connect the
# available tools to the agent after instantiation.
agents:
  # Background Researcher
  - role: background_researcher
    goal: >
      Find and fetch the most relevant papers or articles on a given topic
    backstory: >
      You are responsible for fetching the most up-to-date articles and papers on
      a given topic. You do this by searching for articles and papers using your
      available tools and converting them to markdown for easy reading.
    toolsets:
      - doc_conversion
      - research

  # Research Citation Reviewer
  # research_citation_reviewer
  - role: research_citation_reviewer
    goal: >
      Find all background topics a reader needs to understand in order to make
      sense of the content of an article
    backstory: >
      Your goal is to

      Given the text of a paper or article, you break down the key topics that a
      reader would need to know ahead of time in order to read the content of the
      article and understand it. You then cross-reference these topics with any
      citations available in the article to find additional source material for a
      reader to look into in order to gain the necessary background information.
      If you find a background topic with no citations, you flag that as well.

# Tasks
tasks:
  # Convert Document
  - description: >
      Convert a given document to markdown using available tools
    expected_output: >
      A markdown representation of a document
    agent: background_researcher

  # Conduct Article Search
  - description: >
      Search for articles and papers related to a given topic
    expected_output: >
      A list of paths or links to articles and papers related to a given topic,
      sorted by relevance
    agent: background_researcher

  # Find Background Topics
  - description: >
      Review the content of an article and identify the key topics of background
      knowledge that a reader would need to understand in order to understand the
      article.
    expected_output: >
      A JSON list of objects, each containing the field "topic" with a string
      description of the topic, the field "passages" with a list of strings where
      the topic is referenced, and the field "citations" with a list of strings
      representing existing citations from the article that relate to the given
      topic.
    agent: research_citation_reviewer

# Tools
tools:
  # NOTE: Intentionally match Claude Desktop schema
  mcpServers:
    docling:
      command: uvx
      args:
        - --from
        - docling-mcp@1.2.0
        - docling-mcp-server
      env:
        UV_PYTHON: "3.12"
      kwargs:
        connect_timeout: 120

    arxiv:
      command: uvx
      args:
        - arxiv-mcp-server
        - --storage-path
        # TODO: Make this configurable?
        - ./paper_storage

  toolsets:
    doc_conversion:
      - convert-document-into-docling-document
      - export-docling-document-to-markdown
      - is-document-in-local-cache
    research:
      - search-papers
