# NOTE: Intentionally match Claude Desktop schema
mcpServers:
  docling:
    command: uvx
    args:
      - --from
      - docling-mcp@1.2.0
      - docling-mcp-server
    env:
      UV_PYTHON: "3.12"
    kwargs:
      connect_timeout: 120

  arxiv:
    command: uvx
    args:
      - arxiv-mcp-server
      - --storage-path
      # TODO: Make this configurable?
      - ./paper_storage

toolsets:
  doc_conversion:
    - convert-document-into-docling-document
    - export-docling-document-to-markdown
    - is-document-in-local-cache
  research:
    - search-papers
